### PR TITLE
Fix links interpolations

### PR DESCRIPTION
**Pull request by lex111**
Not all footer links work now.

cc @SachaG

### CODE REVIEW

**Comment by SachaG** [comment]
Ah right, that's because Vulcan and Gatsby use different syntaxes… (Vulcan doesn't have the `$`). But I think we still need the quotes though, so it should be `href="${link}"`?

**Comment by lex111** [comment]
The Discord links don't have quotes, so maybe they are not needed?

https://github.com/StateOfJS/state-of-js-graphql-results-api/blob/dec668b9ad8a677d08c2cef034263085d2d21bbc/src/i18n/en-US/common.yml#L130

**Comment by SachaG** [comment]
I think it's more correct to have them if possible

**Comment by lex111** [comment]
Done :heavy_check_mark:

**Comment by SachaG** [comment]
Great work, thanks!

**Pull request merged**
