### PR TITLE
Fix translation keys in model YAML and CZ localisation 🇨🇿

### PR DESCRIPTION
**Pull request by adamkudrna**
@SachaG It looks like the model YAML was out of sync with actual keys used so I tried to fix it.

### CODE REVIEW

**Comment by adamkudrna** [comment]
I'm confused of the conflicts, I don't see any reason for them…

**Comment by SachaG** [comment]
Thanks! Sorry about the out-of-date model file, maybe it's a bad idea to have it and we should just keep `en-US` as reference… The only thing the model does is add ` # TODO` comments but I don't know if that's helpful at all…?

**Comment by adamkudrna** [comment]
@SachaG Well I haven't checked how the translation files are created and maintained but I don't think it will work without too much hassle if the process isn't automated so we can be sure that all translation files always contain up-to-date keys. Maybe there could be a GitHub action watching for changes in translations in every PR and the developers would be responsible for keeping the translation keys in all languages up-to-date…?

Should the `model` file be maintained manually, I agree it's better to claim the English translation for the starting point.

In my case, I didn't make use of the `TODO` comments, I just deleted them all before making the PR. But I don't want to speak for others, I just didn't use them because I created the translation almost at once (half on Thursday night, the rest on Friday).

**Comment by SachaG** [comment]
Yeah currently it's a manual process so I think you're right, it's better to remove the `model` files until we figure out a way to generate it automatically.

**Pull request merged**
