### PR TITLE
🇳🇱 Dutch translations

### PR DESCRIPTION
**Pull request by MaxAltena**
Dutch translations for the API.

Progress within #146

### CODE REVIEW

**Comment by MaxAltena** [comment]
In addition, some other language `.yml` files changed due to Prettier running on save when adding `nl-NL` to `results.yml`

**Comment by MaxAltena** [comment]
Ready to merge!

**Comment by MaxAltena** [comment]
@SachaG @myakura

Ready to merge BTW.

**Comment by SachaG** [comment]
Thanks so much! I'll take care of it :)

**Comment by SachaG** [comment]
Before I merge, could you undo the changes to the non-Dutch language files just to avoid any potential conflicts?

**Comment by MaxAltena** [comment]
@SachaG Should now be fixed!

**Comment by SachaG** [comment]
Thanks! I'll merge it now :)

**Pull request merged**
