### PR TITLE
Add Czech translation 🇨🇿

### PR DESCRIPTION
**Pull request by adamkudrna**

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks so much!

**Comment by SachaG** [comment]
Thanks again for your help! We have added a few more strings to translate: https://github.com/StateOfJS/state-of-js-graphql-results-api/issues/50#issuecomment-729387462

**Comment by adamkudrna** [comment]
@SachaG When do you plan to publish the results? I'm quite busy now but it should be ready by Monday, is that alright?

**Comment by SachaG** [comment]
Yeah Monday is fine, we'll try to publish them maybe thursday?

**Comment by adamkudrna** [comment]
Hey @SachaG, I'm on it, "only" 80 % of `state_of_css_2020.yml` is ahead of me, everything else is translated.

Sorry for the delay, my originally _quite busy_ week has quickly become _heavily overloaded_. I guess there's one last hour of work I might be able to find tomorrow/today/on Friday.

**Comment by SachaG** [comment]
No problem! We've pushed back the launch date to Monday anyway, we're still waiting on some other content. So no hurry :)

**Pull request merged**
